import certifications from "../../assets/images/certifications/certifications.jpg";
import certOeko from "../../assets/images/certifications/certificacion-oeko.png";
import certStandar from "../../assets/images/certifications/certificacion-standard.png";
import certOrganic from "../../assets/images/certifications/certificacion-organic.png";
import certReduzco from "../../assets/images/certifications/certificacion-reduzco.png";
import certLca from "../../assets/images/certifications/icon-lca.svg";
import certCompact from "../../assets/images/certifications/certificacion-compact.png";
import certEx from "../../assets/images/certifications/certificacion-exchange.png";
import certCircular from "../../assets/images/certifications/certificacion-circular.png";

// certifications english
export const certificationsEN = {
  ensuringTrans: {
    sectionName: "Ferre / Sustainability / Certifications",
    title: "Ensuring transparency",
    img: certifications,
    paragraphs: [
      "All of our sustainability claims are supported by the most respected third-party certifications, as well as by studies we have conducted using LCA (Life Cycle Assessment) methodology, which have also been third-party reviewed.",
    ],
  },
  cert: {
    title: "Certifications",
    certsItem: [
      {
        img: certOeko,
        title: "Standard 100 of OEKO-TEX®",
        paragraphs: [
          "Ferre is OEKO-TEX® STANDARD 100 certified. It is one of the world’s best-known labels for textiles tested for harmful substances. Represents customer trust and high product safety. The test is performed by independent OEKO-TEX® partner institutes and numerous regulated and unregulated substances are taken into account, which can be harmful to human health. In many cases, the limit values of the STANDARD 100 go beyond national and international requirements.",
        ],
      },
      {
        img: certStandar,
        title: "Global Recycled Standard (GRS)",
        paragraphs: [
          "Ferre is GRS certified. Global Recycled Standard (GRS) is an international, voluntary, full product standard that sets requirements for third-party certification of recycled content, chain of custody, social and environmental practices and chemical restrictions. The GRS is intended to meet the needs of companies looking to verify the recycled content of their products and to verify responsible social, environmental and chemical practices in their production.",
        ],
      },
      {
        img: certOrganic,
        title: "OCS Blended – Organic Content Standard",
        paragraphs: [
          "Ferre is OCS certified. The Organic Content Standard (OCS) applies to any non-food product containing 5-100 percent organic material. It verifies the presence and amount of organic material in a final product. Further OCS tracks the flow of a raw material from its source to the final product. This process is then certified by an accredited third party.",
        ],
      },
      {
        img: certReduzco,
        title: "I calculate, I compensate, I reduce",
        paragraphs: [
          "Ferre is “I calculate, I compensate, I reduce” certified. This carbon footprint registry, created by the government of Spain, collects the efforts of Spanish organizations in calculating and reducing greenhouse gas emissions generated by their activity. In turn, it facilitates the possibility of offsetting all or part of their carbon footprint, through a series of forestry projects located in the national territory. These projects include numerous environmental and social benefits, among which is the absorption of carbon dioxide from the atmosphere, also known as carbon sequestration.",
        ],
      },

      {
        img: certLca,
        title: "LCA",
        paragraphs: [
          "At Ferre we use the Life Cycle Assessment (LCA) methodology to measure the environmental footprint of our products from cradle-to-grave. For this, we observe metrics such as the carbon footprint, the water footprint, the use of chemicals and others. This assessment of the environmental impact of our products has been third-party reviewed by AITEX, Universitat de València and UNESCO, to ensure transparency.",
        ],
      },
    ],
  },
  assoCommit: {
    title: "Associations and Commitments",
    assoCommitsItem: [
      {
        img: certCompact,
        title: "UN Global Compact",
        paragraphs: [
          "Ferre is a signatory to the UN Global Compact, a United Nations initiative to encourage businesses worldwide to align strategies and operations with universal principles on human rights, labour, environment and anti-corruption, and take actions that advance societal goals.",
        ],
      },
      {
        img: certEx,
        title: "Textile Exchange",
        paragraphs: [
          "Ferre is a member of Textile Exchange, a global non-profit organization that focuses on minimizing the harmful impacts of the global textile industry and maximizing its positive effects, as well as helping to establish good practices and fair business models throughout the supply chain.",
        ],
      },
      {
        img: certCircular,
        title: "Circular Fashion",
        paragraphs: [
          "Ferre is a member of Circular Fashion, a sustainable change agency creating product and system innovation for a circular economy in fashion and textiles.",
        ],
      },
    ],
  },
};

// certifications panish
export const certificationsES = {
  ensuringTrans: {
    sectionName: "Ferre / Sostenibilidad / Certificaciones",
    title: "Asegurar la transparencia",
    img: certifications,
    paragraphs: [
      "Todas nuestras afirmaciones sobre sostenibilidad están respaldadas por las certificaciones más respetadas, así como por los estudios que hemos realizado utilizando la metodología LCA (Life Cycle Assessment), que a su vez han sido revisados por organismos independientes.",
    ],
  },
  cert: {
    title: "Certificaciones",
    certsItem: [
      {
        img: certOeko,
        title: "Standard 100 of OEKO-TEX®",
        paragraphs: [
          "Ferre tiene la certificación STANDARD 100 de OEKO-TEX®. Esta es una de las certificaciones más conocidas dentro de los tests de sustancias nocivas en productos textiles. Avala la confianza del cliente y la alta seguridad del producto. La prueba es realizada por institutos asociados independientes OEKO-TEX® y se tienen en cuenta numerosas sustancias reguladas y no reguladas que pueden ser perjudiciales para la salud humana. En muchos casos, las exigencias del STANDARD 100 superan los requisitos nacionales e internacionales.",
        ],
      },
      {
        img: certStandar,
        title: "Global Recycled Standard (GRS)",
        paragraphs: [
          "Ferre tiene la certificación Global Recycled Standard (GRS). El Estándar Global de Reciclaje es un estándar de producto internacional, voluntario y completo, que fija requisitos para la certificación por parte de terceros de contenido reciclado, cadena de custodia, prácticas sociales y medioambientales, y restricciones químicas. El GRS está pensado para satisfacer las necesidades de empresas que buscan verificar el contenido reciclado de sus productos y para verificar prácticas sociales, medioambientales y químicas responsables en su producción.",
        ],
      },
      {
        img: certOrganic,
        title: "OCS Blended – Organic Content Standard",
        paragraphs: [
          "Ferre tiene la certificación OCS. El Estándar de Contenido Orgánico (OCS por sus siglas en inglés) se aplica a productos no alimentarios que contengan un 5-100% de materia orgánica. Verifica la presencia y cantidad de materia orgánica en un producto final. Además, OCS hace un seguimiento del flujo de una materia prima desde su origen al producto final. Una vez realizado el seguimiento, este proceso es certificado por un tercero acreditado.",
        ],
      },

      {
        img: certReduzco,
        title: "Calculo, compenso, reduzco",
        paragraphs: [
          "Ferre tiene la certificación “Calculo, compenso, reduzco”. Este registro de huella de carbono, creado por el gobierno de España, recoge los esfuerzos de las organizaciones españolas en el cálculo y reducción de las emisiones de gases de efecto invernadero que genera su actividad. A su vez, les facilita la posibilidad de compensar toda o parte de su huella de carbono, mediante una serie de proyectos forestales ubicados en territorio nacional. Estos proyectos, integran numerosos beneficios ambientales y sociales, entre los que se encuentra la absorción de dióxido de carbono de la atmósfera, también conocida como secuestro de carbono.",
        ],
      },

      {
        img: certLca,
        title: "LCA",
        paragraphs: [
          "En Ferre utilizamos la metodología Life Cycle Assessment (LCA) para medir la huella medioambiental de nuestros productos a lo largo de todo su ciclo de vida. Para ello observamos métricas como la huella de carbono, la huella hídrica, el uso de químicos y otras. Esta evaluación del impacto ambiental de nuestros productos ha sido revisada por organismos independientes -AITEX, Universitat de València y UNESCO-, para garantizar la transparencia.",
        ],
      },
    ],
  },
  assoCommit: {
    title: "Asociaciones y Compromisos",
    assoCommitsItem: [
      {
        img: certCompact,
        title: "Pacto Mundial de la ONU",
        paragraphs: [
          "Ferre es firmante del Pacto Mundial de la ONU, una iniciativa de las Naciones Unidas para llamar a las empresas de todo el mundo a alinear sus estrategias y operaciones con los principios universales sobre derechos humanos, trabajo, medio ambiente y anticorrupción, y tomar acciones que promuevan los objetivos sociales.",
        ],
      },
      {
        img: certEx,
        title: "Textile Exchange",
        paragraphs: [
          "Ferre es miembro de Textile Exchange, una organización global sin ánimo de lucro cuyo objetivo es minimizar los impactos negativos de la industria textil global y maximizar sus efectos positivos, así como ayudar a establecer buenas prácticas y modelos de negocio justos en toda la cadena de suministro.",
        ],
      },
      {
        img: certCircular,
        title: "Circular Fashion",
        paragraphs: [
          "Ferre es miembro de Circular Fashion, una agencia de cambio sostenible que crea productos y sistemas innovadores para impulsar la economía circular en la moda y la industria textil.",
        ],
      },
    ],
  },
};
